version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" #dns
      - "53:53/udp" #dns
      - "67:67/udp" #dhcp
      - "8085:80/tcp" #web
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'YourPassword'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
